import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  container: {
    padding: '32px 32px 24px 32px',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    position: 'relative',
  },
  backButton: {
    position: 'absolute',
    top: '32px',
    left: '32px',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#6b7280',
    transition: 'color 0.2s ease',
  },
  title: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#111827',
    margin: '0 0 8px 0',
    textAlign: 'center',
  },
  inputGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  label: {
    fontSize: '14px',
    fontWeight: '500',
    color: '#374151',
    textAlign: 'left',
  },
  input: {
    width: '100%',
    padding: '12px 16px',
    fontSize: '16px',
    border: '1px solid #d1d5db',
    borderRadius: '8px',
    outline: 'none',
    transition: 'border-color 0.2s ease',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    boxSizing: 'border-box',
  },
  errorText: {
    fontSize: '12px',
    color: '#ef4444',
    marginTop: '4px',
    display: 'block',
    textAlign: 'left',
  },
  tosContainer: {
    backgroundColor: '#f9fafb',
    borderRadius: '24px',
    padding: '16px',
    border: '1px solid #f3f4f6',
  },
  tosLabel: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '12px',
    fontSize: '12px',
    color: '#76767B',
    cursor: 'pointer',
    textAlign: 'left',
  },
  checkbox: {
    width: '16px',
    height: '16px',
    cursor: 'pointer',
    flexShrink: 0,
    marginTop: '2px',
    accentColor: '#007bff',
  },
  tosText: {
    lineHeight: '1.5',
  },
  link: {
    fontWeight: 'bold',
    color: '#76767B',
    background: 'none',
    border: 'none',
    padding: '0',
    cursor: 'pointer',
    textDecoration: 'none',
    transition: 'color 0.2s ease',
  },
  button: {
    width: '100%',
    background: 'linear-gradient(to right, #a855f7, #ec4899)',
    color: 'white',
    fontWeight: '600',
    fontSize: '16px',
    padding: '16px',
    borderRadius: '12px',
    border: 'none',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  buttonDisabled: {
    opacity: 0.5,
    cursor: 'not-allowed',
  },
};
